import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

/**
 * Local image store for NORVI.
 *
 * Uploaded images are written to disk (default `data/uploads`) instead of an
 * external bucket, so a self-hosted NORVI needs no cloud credentials. Files are
 * served back through `GET /api/files/:id` — see `src/api/index.ts`.
 */

/** Image formats NORVI accepts for vision. */
export const ALLOWED_IMAGE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
] as const;

const EXTENSION: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

/** Hard cap per image — keeps a runaway upload from filling the disk. */
export const MAX_IMAGE_BYTES = 12 * 1024 * 1024;

/** Ids are generated by us, so anything else is a path-traversal attempt. */
const ID_PATTERN = /^[a-f0-9]{32}\.(jpg|png|webp)$/;

function uploadDir(): string {
  return resolve(process.env.UPLOAD_DIR?.trim() || "data/uploads");
}

export function isAllowedImageType(mediaType: string): boolean {
  return (ALLOWED_IMAGE_TYPES as readonly string[]).includes(mediaType);
}

/** Normalises what browsers and phones report to a media type we support. */
export function normaliseImageType(mediaType: string | undefined, filename?: string): string | null {
  const raw = (mediaType ?? "").split(";")[0]!.trim().toLowerCase();
  if (raw === "image/jpg" || raw === "image/pjpeg") return "image/jpeg";
  if (isAllowedImageType(raw)) return raw;

  // Some Android pickers send an empty or generic type — fall back to the extension.
  const ext = filename?.toLowerCase().match(/\.(jpe?g|png|webp)$/)?.[1];
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "png") return "image/png";
  if (ext === "webp") return "image/webp";
  return null;
}

export interface StoredImage {
  /** File name on disk, also the public id in `/api/files/:id`. */
  id: string;
  url: string;
  mediaType: string;
  bytes: number;
}

/** Writes one image to the upload directory and returns its public reference. */
export async function storeImage(data: Uint8Array, mediaType: string): Promise<StoredImage> {
  const ext = EXTENSION[mediaType];
  if (!ext) throw new Error(`Nicht unterstütztes Bildformat: ${mediaType}`);

  const dir = uploadDir();
  await mkdir(dir, { recursive: true });

  const id = `${crypto.randomUUID().replace(/-/g, "")}.${ext}`;
  await writeFile(join(dir, id), data);

  return { id, url: `/api/files/${id}`, mediaType, bytes: data.byteLength };
}

/** Reads a stored image back, or null when the id is unknown or malformed. */
export async function readImage(
  id: string,
): Promise<{ data: Uint8Array; mediaType: string } | null> {
  if (!ID_PATTERN.test(id)) return null;
  const ext = id.split(".").pop()!;
  const mediaType = ext === "jpg" ? "image/jpeg" : `image/${ext}`;
  try {
    const data = await readFile(join(uploadDir(), id));
    return { data: new Uint8Array(data), mediaType };
  } catch {
    return null;
  }
}

/** Absolute URL of a stored image — vision models need to fetch it themselves. */
export function absoluteFileUrl(path: string, requestUrl: string): string {
  if (/^https?:\/\//i.test(path)) return path;
  const base = (process.env.WEBSITE_URL?.trim() || new URL(requestUrl).origin).replace(/\/+$/, "");
  return `${base}${path.startsWith("/") ? path : `/${path}`}`;
}

/** File id inside a `/api/files/:id` reference, or null for anything else. */
export function fileIdFromUrl(url: string): string | null {
  const match = url.match(/\/api\/files\/([^/?#]+)$/);
  return match?.[1] ?? null;
}

/**
 * Inlines a stored image as a `data:` URL.
 *
 * The image bytes themselves are handed to the model — a home server is not
 * reachable from a hosted model provider, so a link would never work.
 */
export async function imageAsDataUrl(url: string): Promise<string | null> {
  const id = fileIdFromUrl(url);
  if (!id) return null;
  const image = await readImage(id);
  if (!image) return null;
  const base64 = Buffer.from(image.data).toString("base64");
  return `data:${image.mediaType};base64,${base64}`;
}
